ls:
  "{mods,eslint,scripts}/**/*":
    .ts: kebab-case
    .tsx: kebab-case
    .d.ts: kebab-case
    .json: kebab-case
    .sh: kebab-case
    .md: kebab-case | screamingsnakecase
ignore:
  - node_modules
  - mods/*/.claude-plugin/types
